import * as z from "zod";

export const formScheme = z.object({
    text : z.string().min(1 , {
        message : " Text is required"
    }),
    sourceLang : z.string().min(1 , {
        message : " Text is required"
    }),
    targetLang : z.string().min(1 , {
        message : " target Language is required"
    }),
})

export const languages = [
    { label: "afrikaans", name: "Afrikaans" },
    { label: "amharic", name: "Amharic" },
    { label: "arabic", name: "Arabic" },
    { label: "asturian", name: "Asturian" },
    { label: "azerbaijani", name: "Azerbaijani" },
    { label: "bashkir", name: "Bashkir" },
    { label: "belarusian", name: "Belarusian" },
    { label: "bulgarian", name: "Bulgarian" },
    { label: "bengali", name: "Bengali" },
    { label: "breton", name: "Breton" },
    { label: "bosnian", name: "Bosnian" },
    { label: "cebuano", name: "Cebuano" },
    { label: "czech", name: "Czech" },
    { label: "welsh", name: "Welsh" },
    { label: "danish", name: "Danish" },
    { label: "german", name: "German" },
    { label: "greek", name: "Greek" },
    { label: "english", name: "English" },
    { label: "spanish", name: "Spanish" },
    { label: "estonian", name: "Estonian" },
    { label: "persian", name: "Persian" },
    { label: "finnish", name: "Finnish" },
    { label: "french", name: "French" },
    { label: "western frisian", name: "Western Frisian" },
    { label: "irish", name: "Irish" },
    { label: "gaelic; scottish gaelic", name: "Gaelic; Scottish Gaelic" },
    { label: "galician", name: "Galician" },
    { label: "gujarati", name: "Gujarati" },
    { label: "hausa", name: "Hausa" },
    { label: "hebrew", name: "Hebrew" },
    { label: "hindi", name: "Hindi" },
    { label: "croatian", name: "Croatian" },
    { label: "haitian; haitian creole", name: "Haitian; Haitian Creole" },
    { label: "hungarian", name: "Hungarian" },
    { label: "armenian", name: "Armenian" },
    { label: "indonesian", name: "Indonesian" },
    { label: "igbo", name: "Igbo" },
    { label: "icelandic", name: "Icelandic" },
    { label: "italian", name: "Italian" },
    { label: "japanese", name: "Japanese" },
    { label: "javanese", name: "Javanese" },
    { label: "georgian", name: "Georgian" },
    { label: "kazakh", name: "Kazakh" },
    { label: "central khmer", name: "Central Khmer" },
    { label: "kannada", name: "Kannada" },
    { label: "korean", name: "Korean" },
    { label: "ganda", name: "Ganda" },
    { label: "lao", name: "Lao" },
    { label: "lithuanian", name: "Lithuanian" },
    { label: "latvian", name: "Latvian" },
    { label: "malagasy", name: "Malagasy" },
    { label: "macedonian", name: "Macedonian" },
    { label: "malayalam", name: "Malayalam" },
    { label: "mongolian", name: "Mongolian" },
    { label: "marathi", name: "Marathi" },
    { label: "malay", name: "Malay" },
    { label: "burmese", name: "Burmese" },
    { label: "nepali", name: "Nepali" },
    { label: "dutch; flemish", name: "Dutch; Flemish" },
    { label: "norwegian", name: "Norwegian" },
    { label: "oriya", name: "Oriya" },
    { label: "panjabi; punjabi", name: "Panjabi; Punjabi" },
    { label: "polish", name: "Polish" },
    { label: "portuguese", name: "Portuguese" },
    { label: "romanian; moldavian; moldovan", name: "Romanian; Moldavian; Moldovan" },
    { label: "russian", name: "Russian" },
    { label: "sindhi", name: "Sindhi" },
    { label: "slovak", name: "Slovak" },
    { label: "slovenian", name: "Slovenian" },
    { label: "somali", name: "Somali" },
    { label: "albanian", name: "Albanian" },
    { label: "serbian", name: "Serbian" },
    { label: "sundanese", name: "Sundanese" },
    { label: "swedish", name: "Swedish" },
    { label: "swahili", name: "Swahili" },
    { label: "tamil", name: "Tamil" },
    { label: "thai", name: "Thai" },
    { label: "tagalog", name: "Tagalog" },
    { label: "tswana", name: "Tswana" },
    { label: "turkish", name: "Turkish" },
    { label: "ukrainian", name: "Ukrainian" },
    { label: "urdu", name: "Urdu" },
    { label: "uzbek", name: "Uzbek" },
    { label: "vietnamese", name: "Vietnamese" },
    { label: "wolof", name: "Wolof" },
    { label: "xhosa", name: "Xhosa" },
    { label: "yiddish", name: "Yiddish" },
    { label: "yoruba", name: "Yoruba" },
    { label: "chinese", name: "Chinese" },
    { label: "zulu", name: "Zulu" },
  ];
  